### ISSUE TITLE
这个新项目和https://github.com/xkeshi/vue-qrcode的主要区别是什么呢？

### ISSUE THREAD

**Issue by xeoshow** [fengyuanchen/vue-qrcode#1]
这个新项目和  https://github.com/xkeshi/vue-qrcode  的主要区别是什么呢？
谢谢。

**Comment by fengyuanchen** [comment]
This component uses [node-qrcode](https://github.com/soldair/node-qrcode) as QR code generator, and the **xkeshi/vue-qrcode** uses [QRious](https://github.com/neocotic/qrious) which does not support Chinese.
