### ISSUE TITLE
如何将生成的二维码作为图片下载下来呢！

### ISSUE THREAD

**Issue by hzyy** [fengyuanchen/vue-qrcode#10]

**Comment by fengyuanchen** [comment]
1. 生成的二维码是canvas元素，可以调用toDataURL生成图片地址。
2. a元素有一个 download 属性，可以点击下载对应链接。

参考：
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
