### ISSUE TITLE
components能直接用VueQrcode.name? 你确定你在vue cli下用过?

### ISSUE THREAD

**Issue by lifetin** [fengyuanchen/vue-qrcode#13]
![44](https://user-images.githubusercontent.com/10474968/50941587-745c6780-14c0-11e9-86e9-0ceef2c4f5e7.png)

直接报错, 语法都通不过

**Comment by lifetin** [comment]
正常是要
![11](https://user-images.githubusercontent.com/10474968/50941765-1c723080-14c1-11e9-9e73-52150a5cb8ca.png)



发出来,免得别的用户来踩坑

**Comment by fengyuanchen** [comment]
你这ES6基础掌握不扎实啊兄dei，正确用法：

```js
components: {
  VueQrcode, // <vue-qrcode />

  // Or
  [VueQrcode.name]: VueQrcode,  // <qrcode />
}
```
