### ISSUE TITLE
Eye Pattern Of QR

### ISSUE THREAD

**Issue by LTFENG** [fengyuanchen/vue-qrcode#19]
请问能不能 加个 修改 眼睛形状 的 调整？
比如原本的 正方形 可以变成 圆形

<img width="427" alt="Screenshot 2019-07-02 at 4 33 00 PM" src="https://user-images.githubusercontent.com/25564882/60499621-6bb85180-9ceb-11e9-8bbf-c9ea5cbd95a4.png">
<img width="558" alt="Screenshot 2019-07-02 at 5 03 05 PM" src="https://user-images.githubusercontent.com/25564882/60499623-6c50e800-9ceb-11e9-83c9-d1fbdff8b7bd.png">

非常谢谢

**Comment by fengyuanchen** [comment]
这里只是一个 node-qrcode 的封装插件，有问题请去 [`node-qrcode`](https://github.com/soldair/node-qrcode) 提问。
