### ISSUE TITLE
Can I add logo in center of  QR

### ISSUE THREAD

**Issue by biigpongsatorn** [fengyuanchen/vue-qrcode#21]
Can I add a logo to the center of QR?
Or do you have any idea to solve this issue?

**Comment by fengyuanchen** [comment]
Not support that I guess. You can check out the docs of [`node-qrcode`](https://github.com/soldair/node-qrcode) for available features.

**Comment by service-paradis** [comment]
There is an open issue for this:
https://github.com/soldair/node-qrcode/issues/212
