### ISSUE TITLE
Remove canvas whitespace

### ISSUE THREAD

**Issue by yogs22** [fengyuanchen/vue-qrcode#25]
Hi!

Can i remove the canvas whitespace ? that mean just the QR Code in the canvas

![gambar](https://user-images.githubusercontent.com/25165999/87269559-bcb27680-c4f7-11ea-930a-2d00a07bf344.png)

Thanks :)

**Comment by fengyuanchen** [comment]
Just set it with the [`options`](https://github.com/fengyuanchen/vue-qrcode#options) prop.
