### ISSUE TITLE
vue 报错

### ISSUE THREAD

**Issue by maixiaojie** [fengyuanchen/vue-qrcode#29]
"@chenfengyuan/vue-qrcode": "^1.0.2"

vue版本：

"vue": "^2.4.2"

<qrcode :value="prevUrl" :options="{ width: 200 }"></qrcode>

prevUrl: ''

报错：

Error in callback for watcher "$props": "Error: No input text"
```
if (typeof data === 'undefined' || data === '') {
	    throw new Error('No input text')
	  }
```

**Comment by maixiaojie** [comment]
已经找到原因

**Comment by 490626721** [comment]
> 已经找到原因

我也遇到了，请问怎么解决的？

**Comment by huyu456** [comment]
该错误，是value没有值，使用
`<vue-qrcode v-if="value" :value="value" :options="{ width: 152 }"/>`即可，避免后面的兄弟踩坑
