### ISSUE TITLE
unpkg.com 找不到專案

### ISSUE THREAD

**Issue by chuanxd** [fengyuanchen/vue-qrcode#3]
請問相對的連結是？

https://unpkg.com/vue-qrcode 

這個是另一個專案，但我想引入作者的專案

**Comment by fengyuanchen** [comment]
Not publish to NPM yet. You can try [RawGit](https://rawgit.com/): 
- https://cdn.rawgit.com/xkeshi/vue-qrcode/v0.2.0/dist/vue-qrcode.js
- https://cdn.rawgit.com/xkeshi/vue-qrcode/v0.2.0/dist/vue-qrcode.min.js

**Comment by chuanxd** [comment]
thank you for your time
