### ISSUE TITLE
老版本中 option 里的size， 在vue3中需要怎么配置？ 

### ISSUE THREAD

**Issue by XXXXXLXL** [fengyuanchen/vue-qrcode#32]
![image](https://user-images.githubusercontent.com/30036139/114286315-3f209480-9a90-11eb-8412-03cfbaf830bd.png)

新版中的 api 参考， 没有 size 这个属性

**Comment by fengyuanchen** [comment]
请参考 [node-qrcode](https://github.com/soldair/node-qrcode#qr-code-options) 的参数。如果新版本没有了，那应该是已经去掉了。
