### ISSUE TITLE
[Vue warn]: Failed to resolve component: vue-qrcode 

### ISSUE THREAD

**Issue by NaturalDevCR** [fengyuanchen/vue-qrcode#34]
Hi!... i have tried to import it just as stated in the documentation, but... I'm getting this error: 

`[Vue warn]: Failed to resolve component: vue-qrcode `

> main.ts

```
...
import { createApp } from 'vue'
import VueQrcode from "@chenfengyuan/vue-qrcode";
...
let app = createApp(App).provide('store', store)
...
app.component(VueQrcode.name, VueQrcode);
```

Any hints? I'm using script setup for components, but still, I have imported other components before and they work perfectly... 

Thanks in advance

**Comment by fengyuanchen** [comment]
- For Vue 2: `npm install @chenfengyuan/vue-qrcode@^1.0.0`
- For Vue 3: `npm install @chenfengyuan/vue-qrcode@^2.0.0`

**Comment by DharmarajX24** [comment]
For anyone using Nuxt 3: 

**plugins/qr.client.ts**
```ts
import VueQrcode from '@chenfengyuan/vue-qrcode';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('qr-code', VueQrcode);
});
```

**pages/test.vue**
```vue
<template>
  <div>
    <ClientOnly>
      <qr-code :options="{ width: 256 }" value="your_string" />
    </ClientOnly>
  </div>
</template>
```
