### ISSUE TITLE
Vue3 support: TypeError: createElement is not a function

### ISSUE THREAD

**Issue by scholtz** [fengyuanchen/vue-qrcode#37]
Not working with vue3..

TypeError: createElement is not a function

![image](https://user-images.githubusercontent.com/1223439/120924920-62ee0880-c6d6-11eb-813e-0fb75e71e0bd.png)

**Comment by fengyuanchen** [comment]
```shell
npm install @chenfengyuan/vue-qrcode@next
```

**Comment by fengyuanchen** [comment]
In short, for Vue 3, use v2.x, for Vue 2, use v1.x.

**Comment by Gismo1337** [comment]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @chenfengyuan/vue-qrcode@2.

**Comment by fengyuanchen** [comment]
@Gismo1337 Please try to use `@chenfengyuan/vue-qrcode@next`
