### ISSUE TITLE
Export as Image Function Question

### ISSUE THREAD

**Issue by JudeMurphy** [fengyuanchen/vue-qrcode#41]
Not really an issue, but I'm looking to add a download option to my website, is there an easy way to export this as an image?

**Comment by fengyuanchen** [comment]
Just set the `tag` option to `canvas`, and call `canvas.toDataURL()` on the canvas, and then download the image.

Refs:
- Canvas to image: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
- Download image on click button: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download
