### ISSUE TITLE
引用库的时候报了两个错

### ISSUE THREAD

**Issue by wynn186** [fengyuanchen/vue-qrcode#46]
报错信息如下：
warning  in ./node_modules/@chenfengyuan/vue-qrcode/dist/vue-qrcode.esm.js
"export 'defineComponent' was not found in 'vue'

warning  in ./node_modules/@chenfengyuan/vue-qrcode/dist/vue-qrcode.esm.js
"export 'h' was not found in 'vue'

请问作者这个怎么回事，现在项目都打不开了，一直报这两个错

**Comment by fengyuanchen** [comment]
- `@chenfengyuan/vue-qrcode@2.x` for `vue@3.x`.
- `@chenfengyuan/vue-qrcode@1.x` for `vue@2.x`.
