### ISSUE TITLE
Qrcode with text

### ISSUE THREAD

**Issue by ocarlosapenas** [fengyuanchen/vue-qrcode#47]
I'm generating qr code to links, and it's ok. I wanna know if is possible put a text inside or below the qr code with a small phrase, or a word.

**Comment by fengyuanchen** [comment]
Why not just create an element after the QR code?

```html
< figure>
  <vue-qrcode value="Hello, World!" :options="{ width: 200 }"></vue-qrcode>
  <figcaption>A description for the QR code</figcaption>
</figure>
```
