### ISSUE TITLE
Adding Line Space In QR Code Value

### ISSUE THREAD

**Issue by farsidd** [fengyuanchen/vue-qrcode#49]
how can I add line space in the QR code value? It shows everything on one line. Any solution?

**Comment by fengyuanchen** [comment]
Any more details? I do not know what you mean...

**Comment by farsidd** [comment]
I am asking previously that when we scan the qr code it gives us a long string on one line & i want line space in that qr scanned value. Anyway i have achieved this by putting "\n" wherever i want a line space.
