### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by oopyoung** [fengyuanchen/vue-qrcode#5]
value字段的值传中文生成的二维码，扫描出来是乱码的，请问如何解决？

**Comment by fengyuanchen** [comment]
QRious暂不支持中文：https://github.com/neocotic/qrious/issues/62

**Comment by cherishhjl** [comment]
size大小设置后二维码不是完全填充的？

**Comment by fengyuanchen** [comment]
@cherishhjl 关于 size 参数请移步 QRious API：https://github.com/neocotic/qrious#api
