### ISSUE TITLE
hello！请问如何自定义通过二维码扫描下载的文件名称？

### ISSUE THREAD

**Issue by Niyuent** [fengyuanchen/vue-qrcode#51]
不自定义文件名称则最后扫码下载时文件名称为null

        <vue-qrcode :value="fileUrl" :options="{ width: 300 }"></vue-qrcode>

**Comment by fengyuanchen** [comment]
扫描下载的文件名称？跟文件下载地址有关系，好像跟二维码本身没有关系吧？

**Comment by Niyuent** [comment]
噢噢前一个问题后端可以解决。还有一个问题：有没有办法当动态改变二维码value时保持二维码图片不变化？

**Comment by fengyuanchen** [comment]
> 噢噢前一个问题后端可以解决。还有一个问题：有没有办法当动态改变二维码value时保持二维码图片不变化？

不支持。两者是一对一匹配关系。
