### ISSUE TITLE
Size issue with vuex

### ISSUE THREAD

**Issue by quentinus95** [fengyuanchen/vue-qrcode#6]
Hi,

When using this component with Vuex and a custom size, the new QRCode size does not respects the asked size when the QRCode value is updated (we get a small QRCode in a large, white square).

**Comment by fengyuanchen** [comment]
Are you sure it is a problem of this component? If yes, any demo or code for reproduction?

**Comment by quentinus95** [comment]
Hey,

Even without using the size attribute, I get the issue. Here is an extract of code to reproduce:

```html
<qrcode :value="url"></qrcode>
```

```js
data () {
    return {
      url: 'hello'
    }
  },
  mounted () {
    setTimeout(() => {
      this.url = 'hellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohello'
    }, 2000)
  }
```

You get this:

![image](https://user-images.githubusercontent.com/8060564/34413584-a5f5cf3a-ebe4-11e7-9d13-fa2952c47353.png)

And then this: :cry: 

![image](https://user-images.githubusercontent.com/8060564/34413592-b816932a-ebe4-11e7-8910-04387de9ba8b.png)

The two codes should have the same size.

**Comment by fengyuanchen** [comment]
It is the default behaviour (or problem) of the [QRious](https://github.com/neocotic/qrious) library.
