### ISSUE TITLE
Send component to print as canvas 

### ISSUE THREAD

**Issue by MariamCast** [fengyuanchen/vue-qrcode#7]
Hello! 
I'm trying to send my component to print, but what I've searched is that I need to convert it to v-html so I think converting the QR to canvas it would work. 
Can anyone help me please? 

 qrcode :value="value" :options="{size: 200,  foreground: 'black'}" v-html="QRcodigo"

that's my code.

**Comment by matthelosh** [comment]
HI! @MariamCast , I cant see the qrcode on print preview on chromium.. Did you solve it?

**Comment by fengyuanchen** [comment]
You can try to set the `tag` prop to `'img'`.

**Comment by matthelosh** [comment]
Thanks for the suggestion.. it works..
