### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JinxChung** [fengyuanchen/vue-qrcode#9]
![image](https://user-images.githubusercontent.com/15516836/37872490-7d6fc7e6-303b-11e8-895b-6a223f8ea4ac.png)
![image](https://user-images.githubusercontent.com/15516836/37872492-87854c24-303b-11e8-96f8-a4c6b1e65790.png)

报错（error）：
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by fengyuanchen** [comment]
Are you sure the `val` prop you used is supported?
